# autogenerated podfile
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target 'MentalGrowth Test App' do
  
  pod 'DevHelper', :git => 'https://github.com/emvakar/DevHelper.git', :branch => 'master'
  pod 'EKNetworking', :git => 'https://github.com/emvakar/EKNetworking.git', :branch => 'master'
  pod 'YoutubeDirectLinkExtractor'
  pod 'Kingfisher', '~> 5.0'
  
end

