# autogenerated podfile
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target 'MentalGrowth Test App' do

  pod 'DevHelper', :git => 'https://github.com/emvakar/DevHelper.git', :branch => 'master'

end

